### PR TITLE
Compute `ArgKind::Other` width from `text.chars().count()` not `text.len()`

### LINKED ISSUE #449: Incorrect table alignment with special characters
When a table contains some special characters (like `€` or `§`), the alignment isn't applied correctly:
```
tibble::tribble(
  ~col1          , ~col2 ,
  "A (Mio. €)" ,    10 ,
  "B (T €)"    ,    20 ,
  "C §"         ,    10 ,
  "works"        ,    10 ,
  "works too"    ,    10 ,
  "works!!"      ,    10 ,
  "$ works"      ,    10 ,
)
```

Tested on air version `0.8.0`

### PR DESCRIPTION
**Pull request by DavisVaughan**
Closes #449

### CODE REVIEW

File: crates/air_r_formatter/src/r/auxiliary/call_arguments_table.rs [hunk 1]
```diff
@@ -491,7 +491,13 @@ impl ArgKind {
...
                 None => *integer_width,
             },
-            ArgKind::Other { text } => text.len(),
+            ArgKind::Other { text } => {
+                // Unlike with integers and decimals, can't use `text.len()` here in case
+                // Unicode characters are involved. `len()` counts bytes, but we want to
+                // align based on the number of characters that visibly show up in a
+                // user's editor (#449).
+                text.chars().count()
+            }
```
Comment (DavisVaughan) [inline crates/air_r_formatter/src/r/auxiliary/call_arguments_table.rs:500]: We do use `text.len()` to compute `integer_width` in other paths, but that's fine, those can never have Unicode characters and using `len()` there will be a little faster I think.
