### PR TITLE
Fix handling of hugging calls

### LINKED ISSUE #21: Adding hugging in `fn1(fn2())` style calls
```r
abort(glue::glue(
  "Length implied by `dim`, {n_elements}, must match the length of `x`, {n_x}."
))
```

Formatted as this right now

```r
abort(
  glue::glue(
    "Length implied by `dim`, {n_elements}, must match the length of `x`, {n_x}."
  )
)
```

But its quite nice with the hug

(Something about enabling this when the only unnamed argument to a function call is another function call, but should respect that leading line break if user wants to expand!)

(quite common across dplyr and elmer)

### PR DESCRIPTION
**Pull request by lionel-**
Branched from #227 (for access to `Either` type).
Closes #21.

### CODE REVIEW

File: crates/air_r_formatter/tests/specs/r/call.R [hunk 1]
```diff
@@ -641,3 +641,67 @@ fn(
...
+c(list(foobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbazzzzzzzzzfoobarbaz))
+
+# Call: Hugging case
+c(list(foobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbazzzzzzzzzfoobarbaz()))
+
+# Another hugging case
+c(list(foobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbazzzzzzzzzfoobarbaz(
+    1,
+    2
+)))
```
Comment (DavisVaughan) [inline crates/air_r_formatter/tests/specs/r/call.R:666]:
```suggestion
# Call: Recursive hugging case, no breaks
c(list(foobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbazzzzzzzzzfoobarbaz()))

# Call: Recursive hugging case, inner arguments break
c(list(foobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbazzzzzzzzzfoobarbaz(1, 2)))

# Call: Recursive hugging case, persistent newlines
c(list(foobar(
  1,
  2
)))
```

For the 2nd example here, I think it is useful to start with `(1, 2)` flat so you can check how it expands it

And then I think we should add the 3rd case above to check that those persistent newlines kick in in the recursive case as they should

File: crates/air_r_formatter/tests/specs/r/call.R [hunk 2]
```diff
@@ -641,3 +641,67 @@ fn(
...
+
```
Comment (DavisVaughan) [inline crates/air_r_formatter/tests/specs/r/call.R:667]: Here's one more

```r
# Call: Recursive hugging case, persistent line breaks stop hugging
c(list(
  foobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbafoobarbazzzzzzzzzfoobarbaz(1, 2)))
```

File: crates/air_r_formatter/src/r/auxiliary/call_arguments.rs [hunk 3]
```diff
@@ -944,20 +945,53 @@ impl Format<RFormatContext> for FormatAllArgsBrokenOut<'_> {
...
+    // We only consider calls with one argument
+    let Some(item) = items.first() else {
+        return Ok(false);
+    };
+    if items.len() != 1 {
+        return Ok(false);
+    }
+
+    // Unwrap the value to get the `AnyRExpression`
+    let Some(arg) = item.element().node.clone()?.value() else {
```
Comment (DavisVaughan) [inline crates/air_r_formatter/src/r/auxiliary/call_arguments.rs:978]:
```suggestion
    let Some(arg) = item.element().node()?.value() else {
```

File: CHANGELOG.md [hunk 4]
```diff
@@ -2,6 +2,17 @@
...
+- Hugging calls like:
+
+  ```r
+  list(c(
+    1,
+    2
+  ))
+  ```
+
+  are no longer expanded (#21).
```
Comment (DavisVaughan) [inline CHANGELOG.md:14]:
```suggestion
  are no longer fully expanded (#21).
```

**Review by DavisVaughan — APPROVED** [review]

**Comment by lionel-** [comment]
oh I just noticed that these test cases are actually different, and the second one currently fails!

```r
c(list(
    1
) #foo
)

c(list(
  1
)
#foo
)
```

File: crates/air_r_formatter/src/r/auxiliary/call_arguments.rs (hunk 3 above)
Comment (lionel-) [reply crates/air_r_formatter/src/r/auxiliary/call_arguments.rs:978]: The clone is necessary

Comment (lionel-) [reply crates/air_r_formatter/src/r/auxiliary/call_arguments.rs:978]: I can make it work with:

```rust
    let Some(arg) = item.element().node.as_ref().ok() else {
        return Ok(false);
    };

    let Some(arg) = arg.value() else {
        return Ok(false);
    };
```

but I'm not sure that's a win

**Comment by lionel-** [comment]
I had to refactor things a bit to give the formatting method access to the syntax tree so I could check for comments a bit more flexibly. See last commit, should hopefully be reasonable.

File: crates/air_r_formatter/src/r/auxiliary/call_arguments.rs [hunk 5]
```diff
@@ -76,6 +76,326 @@ impl RCallLikeArguments {
             Self::Subset2(node) => node.syntax(),
         }
     }
+
```
Comment (lionel-) [inline crates/air_r_formatter/src/r/auxiliary/call_arguments.rs:79]: This is now a method on `RCallLikeArguments`, hence the big diff as the whole thing moved. It feels right and this gives access to `self` and the syntax elements.

File: crates/air_r_formatter/src/r/auxiliary/call_arguments.rs [hunk 6]
```diff
@@ -76,6 +76,326 @@ impl RCallLikeArguments {
...
+        // First write the most expanded variant because it needs `arguments`.
+        let most_expanded = {
+            let mut buffer = VecBuffer::new(f.state_mut());
+            buffer.write_element(FormatElement::Tag(Tag::StartEntry))?;
+
+            write!(
+                buffer,
+                [FormatAllArgsBrokenOut {
+                    call: self,
```
Comment (lionel-) [inline crates/air_r_formatter/src/r/auxiliary/call_arguments.rs:253]: We can then pass `self` here.

File: crates/air_r_formatter/src/r/auxiliary/call_arguments.rs [hunk 7]
```diff
@@ -919,6 +932,7 @@ impl Format<RFormatContext> for FormatGroupedArgument {
 }
 
 struct FormatAllArgsBrokenOut<'a> {
+    call: &'a RCallLikeArguments,
```
Comment (lionel-) [inline crates/air_r_formatter/src/r/auxiliary/call_arguments.rs:935]: The whole call is now part of this struct. This way we can peek at anything we want if needed.

File: crates/air_r_formatter/src/r/auxiliary/call_arguments.rs [hunk 8]
```diff
@@ -945,7 +959,7 @@ impl Format<RFormatContext> for FormatAllArgsBrokenOut<'_> {
             Ok(())
         });
 
-        let args = if !self.expand && is_hugging_call(self.args)? {
+        let args = if !self.expand && is_hugging_call(self.args, self.call.r_token())? {
```
Comment (lionel-) [inline crates/air_r_formatter/src/r/auxiliary/call_arguments.rs:962]: Taking a peek at the right delimiter so we can check for comments.
